server:
  port: 8899

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://117.50.187.130:7102/testdb
    username: zainzhou_postgres
    password: 14ministrAtor
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall
      max-active: 20
      initial-size: 1
      max-wait: 6000
      min-idle: 1
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 60000
      validation-query: select version()
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 0
    timeout: 5000
    password: 14ministrAtor
    auth: 14ministrAtor
    cluster:
      max-redirects: 5
      nodes: 117.50.187.130:7001,117.50.187.130:7002,117.50.187.130:7003,117.50.187.130:7004,117.50.187.130:7005,117.50.187.130:7006
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

management:
  server:
    port: 9989
  endpoints:
    web:
      base-path: /actuator/z
      exposure:
        include: "*"

rocketmq:
  name-server: 10.106.100.52:9876
  producer:
    group: bus-oms-capital
    send-message-timeout: 5000

logging:
  level:
    root: INFO
    com.zainzhou: INFO

zainzhou:
  alarm:
    enabled: true
    robot: https://open.feishu.cn/open-apis/bot/v2/hook/a29423df-ddfb-4c00-87c5-cee8b3f1edd9
  env: local